baseURL = "https://blog.shabi.id/"
languageCode = "en-us"
title = "iｄ's blog"
theme = "m10c"
paginate = 5

[params]
  author = "id"
  description = "这货不是id"
[[params.social]]
  icon = "github"
  name = "github"
  url = "https://github.com/pcmid"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
